- name: variables example
  hosts: local
  connection: local
  vars:
    course : "Devops"
    Duration : 120hrs
  tasks:
    name: variables
    ansible.builtin.debug:
      msg: "course {{course}} and duration {{Duration}}"