- name: loops concept
  hosts: local
  connection: local
  tasks:
  - name:
    ansible.builtin.debug:
      msg: "{{item}}"
    loop:
      - venkatesh
      - Pavan
  - name:
    ansible.builtin.debug:
      msg: "{{item.intial}}.{{item.name}}"
    loop:
      - {name: 'venkatesh' intial: 'palavai'}
      - {name: pavan intial: 'konidala'}