- name: testing in-built functions
  hosts: local
  connection: local
  tasks:
  - name: min max from a list of numbers
    vars:
      num: [1,2,4,6,8,9]
    ansible.builtin.debug:
      msg: "min number is {{num | min}}, max number is {{num | max}}"
  - name: converting string to list
    vars:
      naam: "one, two, three"
    ansible.builtin.debug:
      msg: "{{naam | split(',') | upper}}"
  